---
- name: Configure blockchain nodes
  hosts: all
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker.io
        - git
